title: Leandro Rocha
author:
  name: Leandro Rocha
  email: ljrocha.dev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  iOS Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: https://ljrocha.com # the base hostname & protocol for your site, e.g. https://example.com

show_excerpts: true

minima:
  skin: dark
  date_format: "%b %-d, %Y"

  social_links:
    twitter: ljrochaCS
    github: ljrocha
    linkedin: ljrocha

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      author: Leandro Rocha
      permalink: /blog/:year/:month/:day/:title.html

# Google Analytics
google_analytics: UA-163383853-1

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
